Декоративные элементы на главной странице
htmlacademy-htmlcss/1826213-gllacy-32 pull request #8
Opened 2021-10-29 11:22 UTC by Denysmogyliuk

---
:mortar_board: [Декоративные элементы на главной странице](https://up.htmlacademy.ru/htmlcss/32/user/1826213/tasks/11)

:boom: https://htmlacademy-htmlcss.github.io/1826213-gllacy-32/8/

2021-10-31 17:36 UTC, vladpovelitsa requested changes
грубых ошибок нет, но есть пара замечаний

2021-10-31 17:36 UTC, vladpovelitsa commented on styles/styles.css
> +  font-family: inherit;
inherit не нужно указывать, это значение по умолчанию

2021-10-31 17:36 UTC, vladpovelitsa commented on styles/styles.css
> +}
а почему ты решил их вынести в фон?

2021-11-01 11:10 UTC, Denysmogyliuk commented on styles/styles.css
> +}
Изображения не меняют своего состоянияпри взаимодействии. Стоит вставить в штмл как <img>? инлайн вроде нет смысла вставлять

2021-11-01 12:57 UTC, Denysmogyliuk commented on styles/styles.css
> +  font-family: inherit;
Убираю, шрифт меняется на Ариал

2021-11-06 22:43 UTC, vladpovelitsa approved these changes
Всё ок

2021-11-06 22:43 UTC, merged